apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-incident-assistant.name" . }}
  labels:
    {{- include "ai-incident-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ai-incident-assistant.name" . }}
